title: Wire an RGB LED
hero_image: images/banner.png
description: How to wire an RGB LED to your Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-08"
steps:
  - title: Wire an RGB LED