---
title: Câbler une LED RVB
hero_image: images/banner.png
description: Comment câbler une LED RVB à ton Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-08"
steps:
  - title: Câbler une LED RVB
